baseurl             = "https://shazow.net/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "build"
#theme               = "shazow"
author              = "Andrey Petrov"
title               = "Andrey Petrov"
pygmentsuseclasses  = true
#disqusshortname     = "shazow.net" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-407051-1"

[permalinks]
fixed = ":title"
blog  = "everything/:slug"

[[menu.main]]
name                   = "Writing"
weight                 = -120
identifier             = "everything"
url                    = "/everything"

[params]
latestpostscount       = 10                            # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Andrey Petrov"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "A doodler and computerer. I like open source, room-scale virtual reality, linux, neovim, and p2p systems. YC alum and Xoogler. Cat person."
email                  = "andrey.petrov@shazow.net"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "favicon.ico"
github                 = "https://github.com/shazow"
highlightjs            = true
lang                   = "en"
linkedin               = "https://linkedin.com/in/shazow"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "https://twitter.com/shazow"
highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
highlightjsStyle     = "darcula"

#avatar                 = "images/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
gravatar             = "andrey.petrov@shazow.net"                # do not use in the same time as avatar
