#!/usr/bin/env bash

# Find the frontmatter
while read line; do
    if [[ "$line" =~ ^#\  ]]; then # Title, emit our own frontmatter
        echo "+++"
        echo "title = \"$(echo -n ${line:2})\"" # echo to avoid printing EOL
        echo "date = \"$(date -I)\""
        echo "+++"
        break
    elif [[ "$line" =~ ^[\-+]{3} ]]; then # Frontmatter, emit it verbatim
        echo $line
        break
    fi
done

# Process the body
while read line; do
    if [[ "$line" =~ \!\[.*\]\(https://(.*)\) ]]; then
        # Download remote images locally, rewrite the image include.
        # FIXME: This doesn't work if there is more than one image on a line
        for url in "${BASH_REMATCH[@]}"; do
            url="https://$url"
            wget -q "$url"
            line=${line//$url/$(basename "$url")}
        done
    fi
    echo $line
done
