[build]
publish = "build"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.136.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.136.5"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.136.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
