name: Publish post from issue

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Post
        run: |
          project_root="$PWD"
          save_to="content/posts/${{ github.event.issue.title }}"
          mkdir "$save_to"
          cd "$save_to"
          $project_root/frontmatterify > index.md << EOF
          ${{ github.event.issue.body }}
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            Automagically sprouted for publishing.

            Merging will publish to: https://shazow.net/posts/${{ github.event.issue.title }}

            Closes #${{ github.event.issue.number }}
          reviewers: ${{ github.repository_owner }}
